### ISSUE TITLE
Checking the battle wave 

### ISSUE THREAD

**Issue by tsungcheyu** [josh-hsu/JoshAutomation#3]
For some difficult battles, it's critical to determine the skill timing.

(1) Group the command set by battle wave  
(2) In battle, check which battle wave is now
(3) Do the battle wave command set, and do normal attack until battle wave over

**Comment by josh-hsu** [comment]
Thanks for your input, I will combine #1 and resolve in next build.

**Comment by josh-hsu** [comment]
This issue has been resolved in App version of 1.40
Please refer to following CL:
50de6376022130faf19ebaf4f63b9237bac65652
8321bba3aeb62b931fce60b69cacf9dfbc0bf9e5

Thank you,
Josh
